---
abstract: 'Scripting www.ruten.com.tw'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: WWW::Ruten
name: WWW-Ruten
no_index:
  directory:
    - inc
    - t
requires:
  Encode: 0
  HTML::Selector::XPath: 0
  HTML::TreeBuilder::XPath: 0
  WWW::Mechanize: 0
  perl: 5.8.0
version: 0.01
